version: '2'
services:
  minhamaedizia:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    network_mode: bridge
#    cpu_shares: 128
#    mem_limit: 128m
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - minhamaedizia.env
    environment:
      - PHP_MEMORY_LIMIT=2048M
      - UPLOAD_MAX_FILESIZE=64M
      - MAGENTO_ROOT=/var/www/html
      - PHP_IDE_CONFIG=serverName=magento_cloud_docker
      - XDEBUG_CONFIG=remote_host=host.docker.internal
      - 'PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pcntl pdo_mysql soap sockets sysvmsg sysvsem sysvshm opcache zip redis xsl xdebug'